name: Golang Test CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Check out code
        uses: actions/checkout@v2
      - name: Generate coverage report
        run: |
          go get -t -v ./...
          chmod +x go.test.sh
          ./go.test.sh
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
